=head1 NAME

Glib::Bytes -  Wrappers for bytes objects in GLib

=cut

=head1 HIERARCHY

  Glib::Boxed
  +----Glib::Bytes



=cut

=for object Glib::Bytes Wrappers for bytes objects in GLib

=head1 DESCRIPTION

In addition to the low-level API documented below, L<Glib> also provides
stringification overloading so that you can treat any C<Glib::Bytes> object as
a normal Perl string.

=cut




=head1 METHODS

=head2 bytes = Glib::Bytes-E<gt>B<new> ($data)

=over

=item * $data (scalar) 

=back

Since: glib 2.32

=head2 integer = $bytes1-E<gt>B<compare> ($bytes2)

=over

=item * $bytes2 (Glib::Bytes) 

=back

Since: glib 2.32

=head2 scalar = $bytes-E<gt>B<get_data> 

Since: glib 2.32

=head2 boolean = $bytes1-E<gt>B<equal> ($bytes2)

=over

=item * $bytes2 (Glib::Bytes) 

=back

Since: glib 2.32

=head2 integer = $bytes-E<gt>B<hash> 

Since: glib 2.32

=head2 unsigned = $bytes-E<gt>B<get_size> 

Since: glib 2.32



=cut


=head1 SEE ALSO

L<Glib>, L<Glib::Boxed>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2011 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Glib> for a full notice.



=cut

