=head1 NAME

Glib::OptionContext -  defines options accepted by the commandline option parser

=cut

=head1 HIERARCHY

  Glib::Boxed
  +----Glib::OptionContext



=cut

=for object Glib::OptionContext defines options accepted by the commandline option parser

=cut




=head1 SEE ALSO

L<Glib>, L<Glib::Boxed>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2011 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Glib> for a full notice.



=cut

