#! /usr/bin/python3
# -*- coding: utf-8 -*-
"""
aptd - apt daemon
"""
# Copyright (C) 2008 Sebastian Heinlein <devel@glatzor.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

__author__ = "Sebastian Heinlein <devel@glatzor.de>"
__state__ = "experimental"

import os
import sys


if __name__ == "__main__":
    # Ensure that the default encoding is set since Python's setlocale doesn't
    # allow to change it. This can be the case if D-Bus activation is used,
    # see LP: #1058038 and http://bugs.python.org/issue16162
    if sys.getfilesystemencoding() == "ascii" and not "LANG" in os.environ:
        os.environ["LANG"] = "C.UTF-8"
        os.execv(sys.argv[0], sys.argv)

    import aptdaemon.core

    aptdaemon.core.main()

# vim:ts=4:sw=4:et
