#!/bin/sh
# /usr/lib/emacsen-common/packages/remove/foo
# [ Sample only -- this script hasn't been tested, so be careful. ]
set -e

FLAVOR=$1
elc_dir=/usr/share/${FLAVOR}/site-lisp/foo

echo remove/foo: Handling removal of emacsen flavor ${FLAVOR}

echo emacsen-common: purging byte-compiled files for ${FLAVOR}
rm -f ${elc_dir}/*.elc
rm -f ${elc_dir}/*.el
rm -f ${elc_dir}/Install.log*
if test -e "${elc_dir}"
then
  rmdir --ignore-fail-on-non-empty "${elc_dir}"
fi

exit 0;
