# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsdialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsDialog_base(object):
    def setupUi(self, SettingsDialog_base):
        SettingsDialog_base.setObjectName("SettingsDialog_base")
        SettingsDialog_base.resize(500, 540)
        self.gridlayout = QtWidgets.QGridLayout(SettingsDialog_base)
        self.gridlayout.setContentsMargins(11, 11, 11, 11)
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.TabWidget = QtWidgets.QTabWidget(SettingsDialog_base)
        self.TabWidget.setObjectName("TabWidget")
        self.AutoRefresh = QtWidgets.QWidget()
        self.AutoRefresh.setObjectName("AutoRefresh")
        self.gridlayout1 = QtWidgets.QGridLayout(self.AutoRefresh)
        self.gridlayout1.setContentsMargins(11, 11, 11, 11)
        self.gridlayout1.setSpacing(6)
        self.gridlayout1.setObjectName("gridlayout1")
        self.textLabel3_2_2 = QtWidgets.QLabel(self.AutoRefresh)
        self.textLabel3_2_2.setWordWrap(False)
        self.textLabel3_2_2.setObjectName("textLabel3_2_2")
        self.gridlayout1.addWidget(self.textLabel3_2_2, 0, 0, 1, 1)
        self.line1_2_2 = QtWidgets.QFrame(self.AutoRefresh)
        self.line1_2_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_2_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_2_2.setObjectName("line1_2_2")
        self.gridlayout1.addWidget(self.line1_2_2, 1, 0, 1, 1)
        self.AutoRefreshCheckBox = QtWidgets.QCheckBox(self.AutoRefresh)
        self.AutoRefreshCheckBox.setObjectName("AutoRefreshCheckBox")
        self.gridlayout1.addWidget(self.AutoRefreshCheckBox, 2, 0, 1, 1)
        self.RefreshRateGroupBox = QtWidgets.QGroupBox(self.AutoRefresh)
        self.RefreshRateGroupBox.setEnabled(True)
        self.RefreshRateGroupBox.setObjectName("RefreshRateGroupBox")
        self.gridlayout2 = QtWidgets.QGridLayout(self.RefreshRateGroupBox)
        self.gridlayout2.setContentsMargins(11, 11, 11, 11)
        self.gridlayout2.setSpacing(6)
        self.gridlayout2.setObjectName("gridlayout2")
        self.textLabel1_4 = QtWidgets.QLabel(self.RefreshRateGroupBox)
        self.textLabel1_4.setWordWrap(False)
        self.textLabel1_4.setObjectName("textLabel1_4")
        self.gridlayout2.addWidget(self.textLabel1_4, 0, 0, 1, 1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.AutoRefreshRateSpinBox = QtWidgets.QSpinBox(self.RefreshRateGroupBox)
        self.AutoRefreshRateSpinBox.setEnabled(False)
        self.AutoRefreshRateSpinBox.setWrapping(True)
        self.AutoRefreshRateSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.AutoRefreshRateSpinBox.setMinimum(10)
        self.AutoRefreshRateSpinBox.setMaximum(300)
        self.AutoRefreshRateSpinBox.setProperty("value", 30)
        self.AutoRefreshRateSpinBox.setObjectName("AutoRefreshRateSpinBox")
        self.hboxlayout.addWidget(self.AutoRefreshRateSpinBox)
        self.gridlayout2.addLayout(self.hboxlayout, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout2.addItem(spacerItem, 0, 2, 1, 1)
        self.gridlayout1.addWidget(self.RefreshRateGroupBox, 3, 0, 1, 1)
        self.RefreshTypeGroupBox = QtWidgets.QGroupBox(self.AutoRefresh)
        self.RefreshTypeGroupBox.setObjectName("RefreshTypeGroupBox")
        self.gridlayout3 = QtWidgets.QGridLayout(self.RefreshTypeGroupBox)
        self.gridlayout3.setContentsMargins(11, 11, 11, 11)
        self.gridlayout3.setSpacing(6)
        self.gridlayout3.setObjectName("gridlayout3")
        self.RefreshCurrentRadioButton = QtWidgets.QRadioButton(self.RefreshTypeGroupBox)
        self.RefreshCurrentRadioButton.setEnabled(False)
        self.RefreshCurrentRadioButton.setChecked(True)
        self.RefreshCurrentRadioButton.setObjectName("RefreshCurrentRadioButton")
        self.gridlayout3.addWidget(self.RefreshCurrentRadioButton, 0, 0, 1, 1)
        self.RefreshAllRadioButton = QtWidgets.QRadioButton(self.RefreshTypeGroupBox)
        self.RefreshAllRadioButton.setEnabled(False)
        self.RefreshAllRadioButton.setObjectName("RefreshAllRadioButton")
        self.gridlayout3.addWidget(self.RefreshAllRadioButton, 1, 0, 1, 1)
        self.gridlayout1.addWidget(self.RefreshTypeGroupBox, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(446, 41, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout1.addItem(spacerItem1, 5, 0, 1, 1)
        self.TabWidget.addTab(self.AutoRefresh, "")
        self.SystemTray = QtWidgets.QWidget()
        self.SystemTray.setObjectName("SystemTray")
        self.gridlayout4 = QtWidgets.QGridLayout(self.SystemTray)
        self.gridlayout4.setContentsMargins(11, 11, 11, 11)
        self.gridlayout4.setSpacing(6)
        self.gridlayout4.setObjectName("gridlayout4")
        self.textLabel3_2_3 = QtWidgets.QLabel(self.SystemTray)
        self.textLabel3_2_3.setWordWrap(False)
        self.textLabel3_2_3.setObjectName("textLabel3_2_3")
        self.gridlayout4.addWidget(self.textLabel3_2_3, 0, 0, 1, 1)
        self.line1_2_3 = QtWidgets.QFrame(self.SystemTray)
        self.line1_2_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_2_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_2_3.setObjectName("line1_2_3")
        self.gridlayout4.addWidget(self.line1_2_3, 1, 0, 1, 1)
        self.SystemTraySettings = SystrayFrame(self.SystemTray)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SystemTraySettings.sizePolicy().hasHeightForWidth())
        self.SystemTraySettings.setSizePolicy(sizePolicy)
        self.SystemTraySettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SystemTraySettings.setObjectName("SystemTraySettings")
        self.gridlayout4.addWidget(self.SystemTraySettings, 2, 0, 1, 1)
        self.TabWidget.addTab(self.SystemTray, "")
        self.Commands = QtWidgets.QWidget()
        self.Commands.setObjectName("Commands")
        self.gridlayout5 = QtWidgets.QGridLayout(self.Commands)
        self.gridlayout5.setContentsMargins(11, 11, 11, 11)
        self.gridlayout5.setSpacing(6)
        self.gridlayout5.setObjectName("gridlayout5")
        self.textLabel3_2_2_2 = QtWidgets.QLabel(self.Commands)
        self.textLabel3_2_2_2.setWordWrap(False)
        self.textLabel3_2_2_2.setObjectName("textLabel3_2_2_2")
        self.gridlayout5.addWidget(self.textLabel3_2_2_2, 0, 0, 1, 2)
        self.line1_2_2_3 = QtWidgets.QFrame(self.Commands)
        self.line1_2_2_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1_2_2_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1_2_2_3.setObjectName("line1_2_2_3")
        self.gridlayout5.addWidget(self.line1_2_2_3, 1, 0, 1, 2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.Commands)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridlayout6 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridlayout6.setContentsMargins(11, 11, 11, 11)
        self.gridlayout6.setSpacing(6)
        self.gridlayout6.setObjectName("gridlayout6")
        self.textLabel1_2 = QtWidgets.QLabel(self.groupBox_3)
        self.textLabel1_2.setEnabled(False)
        self.textLabel1_2.setWordWrap(False)
        self.textLabel1_2.setObjectName("textLabel1_2")
        self.gridlayout6.addWidget(self.textLabel1_2, 0, 0, 1, 1)
        self.PrintCommandLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.PrintCommandLineEdit.setEnabled(False)
        self.PrintCommandLineEdit.setObjectName("PrintCommandLineEdit")
        self.gridlayout6.addWidget(self.PrintCommandLineEdit, 1, 0, 1, 1)
        self.textLabel2_2 = QtWidgets.QLabel(self.groupBox_3)
        self.textLabel2_2.setWordWrap(False)
        self.textLabel2_2.setObjectName("textLabel2_2")
        self.gridlayout6.addWidget(self.textLabel2_2, 2, 0, 1, 1)
        self.ScanCommandLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.ScanCommandLineEdit.setObjectName("ScanCommandLineEdit")
        self.gridlayout6.addWidget(self.ScanCommandLineEdit, 3, 0, 1, 1)
        self.textLabel3_3 = QtWidgets.QLabel(self.groupBox_3)
        self.textLabel3_3.setEnabled(False)
        self.textLabel3_3.setWordWrap(False)
        self.textLabel3_3.setObjectName("textLabel3_3")
        self.gridlayout6.addWidget(self.textLabel3_3, 4, 0, 1, 1)
        self.SendFaxCommandLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.SendFaxCommandLineEdit.setEnabled(False)
        self.SendFaxCommandLineEdit.setObjectName("SendFaxCommandLineEdit")
        self.gridlayout6.addWidget(self.SendFaxCommandLineEdit, 5, 0, 1, 1)
        self.textLabel4 = QtWidgets.QLabel(self.groupBox_3)
        self.textLabel4.setEnabled(False)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridlayout6.addWidget(self.textLabel4, 6, 0, 1, 1)
        self.AccessPCardCommandLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.AccessPCardCommandLineEdit.setEnabled(False)
        self.AccessPCardCommandLineEdit.setObjectName("AccessPCardCommandLineEdit")
        self.gridlayout6.addWidget(self.AccessPCardCommandLineEdit, 7, 0, 1, 1)
        self.textLabel5 = QtWidgets.QLabel(self.groupBox_3)
        self.textLabel5.setEnabled(False)
        self.textLabel5.setWordWrap(False)
        self.textLabel5.setObjectName("textLabel5")
        self.gridlayout6.addWidget(self.textLabel5, 8, 0, 1, 1)
        self.MakeCopiesCommandLineEdit = QtWidgets.QLineEdit(self.groupBox_3)
        self.MakeCopiesCommandLineEdit.setEnabled(False)
        self.MakeCopiesCommandLineEdit.setObjectName("MakeCopiesCommandLineEdit")
        self.gridlayout6.addWidget(self.MakeCopiesCommandLineEdit, 9, 0, 1, 1)
        self.gridlayout5.addWidget(self.groupBox_3, 2, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridlayout5.addItem(spacerItem2, 3, 1, 1, 1)
        self.SetDefaultsButton = QtWidgets.QPushButton(self.Commands)
        self.SetDefaultsButton.setEnabled(True)
        self.SetDefaultsButton.setObjectName("SetDefaultsButton")
        self.gridlayout5.addWidget(self.SetDefaultsButton, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout5.addItem(spacerItem3, 4, 1, 1, 1)
        self.TabWidget.addTab(self.Commands, "")
        self.gridlayout.addWidget(self.TabWidget, 0, 0, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(301, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridlayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.StdButtons = QtWidgets.QDialogButtonBox(SettingsDialog_base)
        self.StdButtons.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.NoButton|QtWidgets.QDialogButtonBox.Ok)
        self.StdButtons.setCenterButtons(False)
        self.StdButtons.setObjectName("StdButtons")
        self.gridlayout.addWidget(self.StdButtons, 1, 1, 1, 1)
        self.textLabel1_4.setBuddy(self.AutoRefreshRateSpinBox)
        self.textLabel1_2.setBuddy(self.PrintCommandLineEdit)
        self.textLabel2_2.setBuddy(self.ScanCommandLineEdit)
        self.textLabel3_3.setBuddy(self.SendFaxCommandLineEdit)
        self.textLabel4.setBuddy(self.AccessPCardCommandLineEdit)
        self.textLabel5.setBuddy(self.MakeCopiesCommandLineEdit)

        self.retranslateUi(SettingsDialog_base)
        self.TabWidget.setCurrentIndex(2)
        self.AutoRefreshCheckBox.toggled['bool'].connect(self.AutoRefreshRateSpinBox.setEnabled)
        self.AutoRefreshCheckBox.toggled['bool'].connect(self.RefreshAllRadioButton.setEnabled)
        self.AutoRefreshCheckBox.toggled['bool'].connect(self.RefreshCurrentRadioButton.setEnabled)
        self.StdButtons.accepted.connect(SettingsDialog_base.accept)
        self.StdButtons.rejected.connect(SettingsDialog_base.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog_base)
        SettingsDialog_base.setTabOrder(self.TabWidget, self.AutoRefreshCheckBox)
        SettingsDialog_base.setTabOrder(self.AutoRefreshCheckBox, self.AutoRefreshRateSpinBox)
        SettingsDialog_base.setTabOrder(self.AutoRefreshRateSpinBox, self.RefreshCurrentRadioButton)
        SettingsDialog_base.setTabOrder(self.RefreshCurrentRadioButton, self.RefreshAllRadioButton)
        SettingsDialog_base.setTabOrder(self.RefreshAllRadioButton, self.PrintCommandLineEdit)
        SettingsDialog_base.setTabOrder(self.PrintCommandLineEdit, self.ScanCommandLineEdit)
        SettingsDialog_base.setTabOrder(self.ScanCommandLineEdit, self.SendFaxCommandLineEdit)
        SettingsDialog_base.setTabOrder(self.SendFaxCommandLineEdit, self.AccessPCardCommandLineEdit)
        SettingsDialog_base.setTabOrder(self.AccessPCardCommandLineEdit, self.MakeCopiesCommandLineEdit)
        SettingsDialog_base.setTabOrder(self.MakeCopiesCommandLineEdit, self.SetDefaultsButton)
        SettingsDialog_base.setTabOrder(self.SetDefaultsButton, self.StdButtons)

    def retranslateUi(self, SettingsDialog_base):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog_base.setWindowTitle(_translate("SettingsDialog_base", "HP Device Manager - Settings"))
        self.textLabel3_2_2.setText(_translate("SettingsDialog_base", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Configure if and when devices are automatically refreshed</span></p></body></html>"))
        self.AutoRefreshCheckBox.setText(_translate("SettingsDialog_base", "&Enable device auto refresh"))
        self.RefreshRateGroupBox.setTitle(_translate("SettingsDialog_base", "Refresh Interval"))
        self.textLabel1_4.setText(_translate("SettingsDialog_base", "&Refresh every:"))
        self.AutoRefreshRateSpinBox.setSuffix(_translate("SettingsDialog_base", " sec"))
        self.RefreshTypeGroupBox.setTitle(_translate("SettingsDialog_base", "Devices to Refresh"))
        self.RefreshCurrentRadioButton.setText(_translate("SettingsDialog_base", "Only &currently selected device"))
        self.RefreshAllRadioButton.setText(_translate("SettingsDialog_base", "&All devices"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.AutoRefresh), _translate("SettingsDialog_base", "Auto Refresh"))
        self.textLabel3_2_3.setText(_translate("SettingsDialog_base", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Configure the behavior of the HP Status Service (hp-systray)</span></p></body></html>"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.SystemTray), _translate("SettingsDialog_base", "System Tray Icon"))
        self.textLabel3_2_2_2.setText(_translate("SettingsDialog_base", "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'DejaVu Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Configure what commands to run for device actions</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("SettingsDialog_base", "Commands"))
        self.textLabel1_2.setText(_translate("SettingsDialog_base", "&Print:"))
        self.textLabel2_2.setText(_translate("SettingsDialog_base", "&Scan:"))
        self.textLabel3_3.setText(_translate("SettingsDialog_base", "Send PC &Fax:"))
        self.textLabel4.setText(_translate("SettingsDialog_base", "&Unload Photo Cards:"))
        self.textLabel5.setText(_translate("SettingsDialog_base", "Make &Copies:"))
        self.SetDefaultsButton.setText(_translate("SettingsDialog_base", "Set &Defaults"))
        self.TabWidget.setTabText(self.TabWidget.indexOf(self.Commands), _translate("SettingsDialog_base", "Commands (Advanced)"))

from .systrayframe import SystrayFrame
