# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Crash_QCH)

add_custom_target(KF5Crash_QCH)
set_target_properties(KF5Crash_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5Crash.tags"
    QHP_NAMESPACE "org.kde.KCrash"
    QHP_NAMESPACE_VERSIONED "org.kde.KCrash.5_64_0"
    QHP_VIRTUALFOLDER "kcrash"
    IMPORTED TRUE
)
set_property(TARGET KF5Crash_QCH PROPERTY LINK_QCHS Qt5Core_QCH)

endif()
