cmd_/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/debian/linux-headers-5.0.0-32-generic/usr/src/linux-headers-5.0.0-32-generic/tools/objtool/builtin-check.o := gcc -Wp,-MD,/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/debian/linux-headers-5.0.0-32-generic/usr/src/linux-headers-5.0.0-32-generic/tools/objtool/.builtin-check.o.d -Wp,-MT,/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/debian/linux-headers-5.0.0-32-generic/usr/src/linux-headers-5.0.0-32-generic/tools/objtool/builtin-check.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -Wno-switch-default -Wno-switch-enum -Wno-packed -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89 -g -I/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include -I/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/arch/x86/include/uapi -I/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/objtool/arch/x86/include -I/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/lib -D"BUILD_STR(s)=$(pound)s" -c -o /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/debian/linux-headers-5.0.0-32-generic/usr/src/linux-headers-5.0.0-32-generic/tools/objtool/builtin-check.o builtin-check.c

source_/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/debian/linux-headers-5.0.0-32-generic/usr/src/linux-headers-5.0.0-32-generic/tools/objtool/builtin-check.o := builtin-check.c

deps_/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/debian/linux-headers-5.0.0-32-generic/usr/src/linux-headers-5.0.0-32-generic/tools/objtool/builtin-check.o := \
  /usr/include/stdc-predef.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/lib/subcmd/parse-options.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/kernel.h \
  /usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h \
  /usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h \
  /usr/include/assert.h \
  /usr/include/features.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/bits/long-double.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/compiler.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/compiler-gcc.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/7/include/stdbool.h \
  /usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitsperlong.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap-16.h \
  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
  /usr/include/byteswap.h \
  builtin.h \
  check.h \
  elf.h \
  /usr/include/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/types/__FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/FILE.h \
  /usr/include/x86_64-linux-gnu/bits/libio.h \
  /usr/include/x86_64-linux-gnu/bits/_G_config.h \
  /usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
  /usr/include/x86_64-linux-gnu/bits/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/stdio2.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/time_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/x86_64-linux-gnu/bits/select2.h \
  /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
  /usr/include/x86_64-linux-gnu/bits/sysmacros.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
  /usr/include/elf.h \
  /usr/include/x86_64-linux-gnu/bits/auxv.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/list.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/poison.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/hashtable.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/bitops.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/bits.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/__ffs.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/__ffz.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/fls.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/__fls.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/fls64.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/find.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/hweight.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/arch_hweight.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/const_hweight.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/atomic.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/asm-generic/bitops/non-atomic.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/hash.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/include/linux/log2.h \
  cfi.h \
  arch.h \
  orc.h \
  /build/linux-hwe-iAAoxd/linux-hwe-5.0.0/tools/objtool/arch/x86/include/asm/orc_types.h \

/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/debian/linux-headers-5.0.0-32-generic/usr/src/linux-headers-5.0.0-32-generic/tools/objtool/builtin-check.o: $(deps_/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/debian/linux-headers-5.0.0-32-generic/usr/src/linux-headers-5.0.0-32-generic/tools/objtool/builtin-check.o)

$(deps_/build/linux-hwe-iAAoxd/linux-hwe-5.0.0/debian/linux-headers-5.0.0-32-generic/usr/src/linux-headers-5.0.0-32-generic/tools/objtool/builtin-check.o):
