#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          lvm2-lvmetad
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: LVM2 metadata daemon
### END INIT INFO

DESC="LVM2 metadata daemon"
DAEMON=/sbin/lvmetad
PIDFILE=/run/lvmetad.pid

do_start_prepare() {
  mkdir -m 0700 -p /run/lvm
}
