#!/bin/sh

dev=$1
id=$2
property=$3

[ -f /var/lib/partman/ext4 ] || exit 0

case $property in
    formatable)
	echo ext4
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)

	case "$fs" in
	    ext4)
		echo ext4
		;;
	esac
	;;
esac
