#!/bin/sh

dev=$1
id=$2
property=$3

[ -f /var/lib/partman/ext3 ] || exit 0

case $property in
    formatable)
	echo ext3
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)

	case "$fs" in
	    ext3)
		echo ext3
		;;
	esac
	;;
esac


