#!/bin/sh

dev=$1
id=$2
method=$3

[ -f /var/lib/partman/ext2 ] || exit 0

case $method in
    formatable)
	echo ext2
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)

	case "$fs" in
	    ext2)
		echo ext2
		;;
	esac
	;;
esac


