#!/bin/sh

dev=$1
id=$2
property=$3

[ -f /var/lib/partman/btrfs ] || exit 0

case $property in
    formatable)
	echo btrfs
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)

	case "$fs" in
	    btrfs)
		echo btrfs
		;;
	esac
	;;
esac


