#!/bin/sh

dev=$1
id=$2
property=$3

[ -f /var/lib/partman/jfs ] || exit 0

case $property in
    formatable)
	echo jfs
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)

	case "$fs" in
	    jfs)
		echo jfs
		;;
	esac
	;;
esac


