#!/bin/sh

dev=$1
id=$2
property=$3

[ -f /var/lib/partman/ntfs ] || exit 0

case $property in
    formatable)
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)

	case "$fs" in
	    ntfs)
		echo ntfs
		;;
	esac
	;;
esac
