cmd_/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/debian/linux-headers-5.0.0-37-generic/usr/src/linux-headers-5.0.0-37-generic/tools/objtool/objtool.o := gcc -Wp,-MD,/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/debian/linux-headers-5.0.0-37-generic/usr/src/linux-headers-5.0.0-37-generic/tools/objtool/.objtool.o.d -Wp,-MT,/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/debian/linux-headers-5.0.0-37-generic/usr/src/linux-headers-5.0.0-37-generic/tools/objtool/objtool.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wshadow -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -Wno-switch-default -Wno-switch-enum -Wno-packed -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89 -g -I/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/include -I/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/arch/x86/include/uapi -I/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/objtool/arch/x86/include -I/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/lib -D"BUILD_STR(s)=$(pound)s" -c -o /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/debian/linux-headers-5.0.0-37-generic/usr/src/linux-headers-5.0.0-37-generic/tools/objtool/objtool.o objtool.c

source_/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/debian/linux-headers-5.0.0-37-generic/usr/src/linux-headers-5.0.0-37-generic/tools/objtool/objtool.o := objtool.c

deps_/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/debian/linux-headers-5.0.0-37-generic/usr/src/linux-headers-5.0.0-37-generic/tools/objtool/objtool.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/bits/long-double.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-linux-gnu/7/include/stddef.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/types/__FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/FILE.h \
  /usr/include/x86_64-linux-gnu/bits/libio.h \
  /usr/include/x86_64-linux-gnu/bits/_G_config.h \
  /usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h \
  /usr/lib/gcc/x86_64-linux-gnu/7/include/stdarg.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/sys_errlist.h \
  /usr/include/x86_64-linux-gnu/bits/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/stdio2.h \
  /usr/lib/gcc/x86_64-linux-gnu/7/include/stdbool.h \
  /usr/include/string.h \
  /usr/include/x86_64-linux-gnu/bits/types/locale_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /usr/include/x86_64-linux-gnu/bits/strings_fortified.h \
  /usr/include/x86_64-linux-gnu/bits/string_fortified.h \
  /usr/include/stdlib.h \
  /usr/include/x86_64-linux-gnu/bits/waitflags.h \
  /usr/include/x86_64-linux-gnu/bits/waitstatus.h \
  /usr/include/x86_64-linux-gnu/bits/floatn.h \
  /usr/include/x86_64-linux-gnu/bits/floatn-common.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/time_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap-16.h \
  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/x86_64-linux-gnu/bits/select2.h \
  /usr/include/x86_64-linux-gnu/sys/sysmacros.h \
  /usr/include/x86_64-linux-gnu/bits/sysmacros.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
  /usr/include/alloca.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-bsearch.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib-float.h \
  /usr/include/x86_64-linux-gnu/bits/stdlib.h \
  /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/lib/subcmd/exec-cmd.h \
  /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/lib/subcmd/pager.h \
  /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/include/linux/compiler.h \
  /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/include/linux/compiler-gcc.h \
  /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/include/asm-generic/bitsperlong.h \
  /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/byteswap.h \
  builtin.h \
  /build/linux-hwe-FLYqTt/linux-hwe-5.0.0/tools/lib/subcmd/parse-options.h \

/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/debian/linux-headers-5.0.0-37-generic/usr/src/linux-headers-5.0.0-37-generic/tools/objtool/objtool.o: $(deps_/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/debian/linux-headers-5.0.0-37-generic/usr/src/linux-headers-5.0.0-37-generic/tools/objtool/objtool.o)

$(deps_/build/linux-hwe-FLYqTt/linux-hwe-5.0.0/debian/linux-headers-5.0.0-37-generic/usr/src/linux-headers-5.0.0-37-generic/tools/objtool/objtool.o):
