# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5GuiAddons_QCH)

add_custom_target(KF5GuiAddons_QCH)
set_target_properties(KF5GuiAddons_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5GuiAddons.tags"
    QHP_NAMESPACE "org.kde.KGuiAddons"
    QHP_NAMESPACE_VERSIONED "org.kde.KGuiAddons.5_64_0"
    QHP_VIRTUALFOLDER "kguiaddons"
    IMPORTED TRUE
)
set_property(TARGET KF5GuiAddons_QCH PROPERTY LINK_QCHS Qt5Gui_QCH)

endif()
