# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Attica_QCH)

add_custom_target(KF5Attica_QCH)
set_target_properties(KF5Attica_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5Attica.tags"
    QHP_NAMESPACE "org.kde.Attica"
    QHP_NAMESPACE_VERSIONED "org.kde.Attica.5_64_0"
    QHP_VIRTUALFOLDER "attica"
    IMPORTED TRUE
)
set_property(TARGET KF5Attica_QCH PROPERTY LINK_QCHS Qt5Core_QCH;Qt5Network_QCH)

endif()
