#!/bin/sh
# vim:set et sts=4 sw=4
#
# ibus-table - The Tables engine for IBus
#
# Copyright (c) 2008-2009 Yu Yuwei <acevery@gmail.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

prefix=/usr
exec_prefix=/usr
datarootdir=${prefix}/share
datadir=${datarootdir}
export IBUS_TABLE_LOCATION=${prefix}/share/ibus-table
export IBUS_TABLE_LIB_LOCATION=/usr/lib/ibus

# Set this variable to something > 0 to get more debug output.
# (Debug output may show up in the log file and/or in the lookup table):
# export IBUS_TABLE_DEBUG_LEVEL=1
#
# Set this to something if you want benchmarking (The profiling output
# will appear in the debug long when "ibus restart" is executed):
# export IBUS_TABLE_PROFILE=yes

for arg in $@; do
	case $arg in
	--xml | -x)
		exec /usr/bin/python3 ${prefix}/share/ibus-table/engine/main.py --xml;;
	--help | -h)
		exec /usr/bin/python3 ${prefix}/share/ibus-table/engine/main.py $@;;
        *)
                if [ "x${IBUS_TABLE_PROFILE}" != "x" ]; then
                    exec /usr/bin/python3 ${prefix}/share/ibus-table/engine/main.py --profile $@
                else
                    exec /usr/bin/python3 ${prefix}/share/ibus-table/engine/main.py $@
                fi
                exit 0
	esac
done

