#!/bin/sh

. /lib/recovery-mode/l10n.sh

if [ "$1" = "test" ]; then
  echo $(eval_gettext "Update grub bootloader")
  exit 0
fi

# FIXME: add this too? how to find out boot device?
#        add menu to ask?
#grub-install
update-grub

echo ""
echo $(eval_gettext "Finished, please press ENTER")
read TMP

exit 0
