#!/usr/bin/python

# debtags - Implement package tags support for Debian
#
# Copyright (C) 2003--2006  Enrico Zini <enrico@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

import sys
from debian import debtags

input = sys.stdin
if len(sys.argv) > 1:
	input = open(sys.argv[1],"r")

#db = read_tag_database(input)
#db = reverse(db)
db = debtags.read_tag_database_reversed(input)
#dummy, db = debtags.read_tag_database_both_ways(input)

for pkg, tags in db.items():
	# Using % here seems awkward to me, but if I use calls to
	# sys.stdout.write it becomes a bit slower
	print("%s:" % (pkg), ", ".join(tags))
