#!/usr/bin/python

# debtags - Implement package tags support for Debian
#
# Copyright (C) 2003--2006  Enrico Zini <enrico@debian.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

from __future__ import print_function

import sys
import re
from debian import debtags

if len(sys.argv) < 2:
	print("Usage: %s tagdb [packagelist]" % (sys.argv[0]), file=sys.stderr)
	sys.exit(1)

full = debtags.DB()
# Read full database
tag_filter = re.compile(r"^special::.+$|^.+::TODO$")
full.read(open(sys.argv[1], "r"), lambda x: not tag_filter.match(x))

# Read the package list and create the subcollection
input = len(sys.argv) > 2 and open(sys.argv[2],"r") or sys.stdin
pkgs = set()
for pkg in input:
	# Tolerate apt-cache search output as well
	pkg, none = pkg.rstrip("\n").split(' - ', 1)
	pkgs.add(pkg)

sub = full.choose_packages(pkgs)

rel_index = debtags.relevance_index_function(full, sub)

# Get all the tags sorted by increasing relevance
tags = sorted(sub.iter_tags(), lambda a, b: cmp(rel_index(a), rel_index(b)))

## And finally print them
for tag in tags:
	print(tag)
	#print(tag, sub.card(tag), full.card(tag), float(sub.card(tag)) / float(full.card(tag)))
