# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Codecs_QCH)

add_custom_target(KF5Codecs_QCH)
set_target_properties(KF5Codecs_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5Codecs.tags"
    QHP_NAMESPACE "org.kde.KCodecs"
    QHP_NAMESPACE_VERSIONED "org.kde.KCodecs.5_64_0"
    QHP_VIRTUALFOLDER "kcodecs"
    IMPORTED TRUE
)
set_property(TARGET KF5Codecs_QCH PROPERTY LINK_QCHS Qt5Core_QCH)

endif()
