# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Bookmarks_QCH)

add_custom_target(KF5Bookmarks_QCH)
set_target_properties(KF5Bookmarks_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5Bookmarks.tags"
    QHP_NAMESPACE "org.kde.KBookmarks"
    QHP_NAMESPACE_VERSIONED "org.kde.KBookmarks.5_64_0"
    QHP_VIRTUALFOLDER "kbookmarks"
    IMPORTED TRUE
)
set_property(TARGET KF5Bookmarks_QCH PROPERTY LINK_QCHS Qt5Widgets_QCH;Qt5Xml_QCH;KF5WidgetsAddons_QCH)

endif()
