DATA_DIR = "/usr/share"
PKG_DATA_DIR = "/usr/share/gnome-tweaks"
GSETTINGS_SCHEMA_DIR = "/usr/share/glib-2.0/schemas"
TWEAK_DIR = "/usr/lib/python3/dist-packages/gtweak/tweaks"
VERSION = "3.28.1"
LOCALE_DIR = "/usr/share/locale"
LIBEXEC_DIR = "/usr/lib/gnome-tweak-tool"
