#! /bin/sh

PREREQ=""
DESCRIPTION="Setting up locales..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

if [ -f /root/rofs/etc/default/locale ]; then
    # use rootfs configured locale
    locale=$(grep -s 'LANG=' /root/rofs/etc/default/locale | sed s/'LANG='// | tr -d '"' )
fi

# commandline
for x in $(cat /proc/cmdline); do
    case $x in
	debian-installer/language=*)
	    language=${x#debian-installer/language=}
	    locale="$(lang2locale "$language")"
	    set_locale="true"
	    ;;
	debian-installer/locale=*)
	    locale=${x#debian-installer/locale=}
	    set_locale="true"
	    ;;
	locale=*)
	    locale=${x#locale=}
	    set_locale="true"
	    ;;
    esac
done

if [ -z "${locale}" ]; then
    # Set a default one
    echo LANG=C.UTF-8 > /root/etc/default/locale
fi

if [ "${set_locale}" ]; then
    LANG=$(grep "^${locale}" /root/usr/share/i18n/SUPPORTED | grep UTF-8 |sed -e 's, .*,,' -e q)
    printf 'LANG="%s"\n' "${LANG}" > /root/etc/default/locale
    printf '%s UTF-8\n' "${LANG}" > /root/etc/locale.gen
    chroot /root /usr/sbin/locale-gen --keep-existing
fi

log_end_msg
