#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling systemd's GPT auto generator..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"
rm -f /root/lib/systemd/system-generators/systemd-gpt-auto-generator
log_end_msg
