#! /bin/sh

PREREQ=""
DESCRIPTION="Regenerating SSL certificate..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions
load_confmodule

log_begin_msg "$DESCRIPTION"

if [ -x /root/usr/sbin/make-ssl-cert ]; then
	chroot /root /usr/sbin/make-ssl-cert generate-default-snakeoil --force-overwrite
fi

log_end_msg
