#!/bin/sh

PREREQ=""
DESCRIPTION="Disabling update-notifier..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# For GNOME, we divert away apt-check to avoid a regular 'apt-get update'
# equivalent in the live session. We want to run update-notifier for crash
# report handling.
chroot /root dpkg-divert --add --rename --quiet \
	/usr/lib/update-notifier/apt-check
ln -sf /bin/true /root/usr/lib/update-notifier/apt-check

# For KDE, adept_notifier's only useful function at the moment is an
# 'apt-get update' equivalent, so we disable it entirely.
rm -f /root/usr/share/autostart/adept_notifier_auto.desktop

# Upgrading the live CD to new releases is probably not a great plan.
chroot /root dpkg-divert --add --rename --quiet \
	/usr/lib/ubuntu-release-upgrader/check-new-release
ln -sf /bin/true /root/usr/lib/ubuntu-release-upgrader/check-new-release
chroot /root dpkg-divert --add --rename --quiet \
	/usr/lib/ubuntu-release-upgrader/check-new-release-gtk
ln -sf /bin/true /root/usr/lib/ubuntu-release-upgrader/check-new-release-gtk

#we don't want gnome-software's service to offer updates on the livecd for
#anything it's plugins support
rm -f /root/etc/xdg/autostart/gnome-software-service.desktop

GNOME_SOFTWARE_SEARCH_PROVIDER=/root/usr/share/gnome-shell/search-providers/org.gnome.Software-search-provider.ini 

if [ -e "${GNOME_SOFTWARE_SEARCH_PROVIDER}" ]; then
    # disable the gnome-software shell search provider
    printf "DefaultDisabled=true\n" >> ${GNOME_SOFTWARE_SEARCH_PROVIDER}
fi

log_end_msg
