#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring power management..."

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

cat <<EOF > /root/var/lib/polkit-1/localauthority/50-local.d/disable-hibernate.pkla
[Disable hibernate in live system]
Identity=unix-user:*
Action=org.freedesktop.upower.hibernate
ResultActive=no
EOF

log_end_msg
