#! /bin/sh

PREREQ=""

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

if [ -d /root/usr/share/kubuntu-default-settings/ ]; then
    echo "[Event]\nhideRestartNotifier=true" >> /root/usr/share/kubuntu-default-settings/kde4-profile/default/share/config/notificationhelper
fi
