#!/bin/sh

# This script handles selecting the IV generation algorithm for crypt_types
# that use variable IV algorithms

. /lib/partman/lib/crypto-base.sh

dev=$2
id=$3
part=$dev/$id

[ -f $part/method ] || exit 0
[ -f $part/crypto_type ] || exit 0
[ -f $part/cipher ] || exit 0

method=$(cat $part/method)
type=$(cat $part/crypto_type)
cipher=$(cat $part/cipher)

if [ $method = crypto ]; then
	crypto_dooption $part $type $cipher ivalgorithm
fi
