#!/bin/sh

case "$reason" in
BOUND6)
	echo "DEVICE6=$interface" > /run/net6-$interface.conf
	echo "IPV6PROTO=dhcp6" >> /run/net6-$interface.conf
	echo "IPV6ADDR=$new_ip6_address" >> /run/net6-$interface.conf
	echo "IPV6NETMASK=$new_ip6_prefixlen" >> /run/net6-$interface.conf
	echo "IPV6DNS0=$new_dhcp6_name_servers" >> /run/net6-$interface.conf
	if [ -n "$new_dhcp6_domain_search" ]; then
		echo "IPV6DOMAINSEARCH=$new_dhcp6_domain_search" >> /run/net6-$interface.conf
	fi
	;;
esac

