# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5XmlGui_QCH)

add_custom_target(KF5XmlGui_QCH)
set_target_properties(KF5XmlGui_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5XmlGui.tags"
    QHP_NAMESPACE "org.kde.KXmlGui"
    QHP_NAMESPACE_VERSIONED "org.kde.KXmlGui.5_64_0"
    QHP_VIRTUALFOLDER "kxmlgui"
    IMPORTED TRUE
)
set_property(TARGET KF5XmlGui_QCH PROPERTY LINK_QCHS Qt5Xml_QCH;Qt5DBus_QCH;Qt5Widgets_QCH;KF5Config_QCH;KF5ConfigWidgets_QCH)

endif()
