# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5WindowSystem_QCH)

add_custom_target(KF5WindowSystem_QCH)
set_target_properties(KF5WindowSystem_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5WindowSystem.tags"
    QHP_NAMESPACE "org.kde.KWindowSystem"
    QHP_NAMESPACE_VERSIONED "org.kde.KWindowSystem.5_64_0"
    QHP_VIRTUALFOLDER "kwindowsystem"
    IMPORTED TRUE
)
set_property(TARGET KF5WindowSystem_QCH PROPERTY LINK_QCHS Qt5Gui_QCH)

endif()
