#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# blacklist vga16fb when vga= or video= given
for x in $(cat /proc/cmdline); do
        case ${x} in
	vga=*|video=*)
		echo "blacklist vga16fb" >> /etc/modprobe.d/initramfs.conf
		;;
	esac
done

# sanity check
[ -z "${blacklist}" ] && exit 0

# write blacklist to modprobe.d
IFS=','
for b in ${blacklist}; do
	echo "blacklist $b" >> /etc/modprobe.d/initramfs.conf
done
