#!/bin/sh -e

# exit if the resolvconf package is installed
[ -x /sbin/resolvconf ] && exit 0

# follow any symlink to find the real file
if [ -e /etc/resolv.conf ]; then
  REALRESOLVCONF=$(readlink --canonicalize /etc/resolv.conf)
else
  REALRESOLVCONF=/etc/resolv.conf
fi

# if an old resolv.conf file exists, restore it
if [ -e $REALRESOLVCONF.pppd-backup.$PPP_IFACE ]; then
  mv -f $REALRESOLVCONF.pppd-backup.$PPP_IFACE $REALRESOLVCONF

  # restart nscd because resolv.conf has changed
  if [ -e /var/run/nscd.pid ]; then
    /etc/init.d/nscd restart || true
  fi
fi

exit 0

