#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright (C) 2018 Canonical
#
# Authors:
#  Andrea Azzarone <andrea.azzarone@canonical.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUTa
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

import gi
gi.require_version('Secret', '1')
from gi.repository import Gio, Secret

SECRETS_SCHEMA = Secret.Schema.new('com.ubuntu.SotwareProperties',
                                   Secret.SchemaFlags.NONE,
                                   {'key': Secret.SchemaAttributeType.STRING})

account_id = Secret.password_lookup_sync(SECRETS_SCHEMA, {'key': 'account-id'}, None)

if account_id:
    settings = Gio.Settings.new('com.ubuntu.SoftwareProperties')
    account_id = settings.set_string('goa-account-id', account_id)
    Gio.Settings.sync()