#!/bin/sh

. /lib/partman/lib/base.sh

dev=$1
id=$2

cd $dev
open_dialog VIRTUAL $id
read_line virtual
close_dialog
if [ "$virtual" = yes ]; then
	exit 0
fi

db_metaget partman-crypto/text/erase_data_partition description
printf "erase_partition\t${RET}\n"

