=head1 NAME

Glib::Param::Boolean -  Wrapper for boolean parameters in GLib

=cut

=head1 HIERARCHY

  Glib::ParamSpec
  +----Glib::Param::Boolean



=cut

=for object Glib::Param::Boolean Wrapper for boolean parameters in GLib
=cut




=head1 SEE ALSO

L<Glib>, L<Glib::ParamSpec>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2011 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Glib> for a full notice.



=cut

