=head1 NAME

Glib::Param::Double -  Wrapper for double parameters in GLib

=cut

=head1 HIERARCHY

  Glib::ParamSpec
  +----Glib::Param::Double



=cut

=for object Glib::Param::Double Wrapper for double parameters in GLib

=for position post_hierarchy

  Glib::ParamSpec
  +----Glib::Param::Float

=cut

=head1 DESCRIPTION

This page documents the extra accessors available for both of the
floating-point type paramspecs: Float and Double.  Perl really only supports
doubles, so all of these methods return NVs (that is, the C type "double"); the
distinction of size is important to the underlying C library and also
determines the data value range.

=cut




=head1 SEE ALSO

L<Glib>, L<Glib::ParamSpec>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2011 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Glib> for a full notice.



=cut

