=head1 NAME

Glib::Param::Enum -  Wrapper for enum parameters in GLib

=cut

=head1 HIERARCHY

  Glib::ParamSpec
  +----Glib::Param::Enum



=cut

=for object Glib::Param::Enum Wrapper for enum parameters in GLib
=cut




=head1 METHODS

=head2 string = $pspec_enum-E<gt>B<get_enum_class> 



=cut


=head1 SEE ALSO

L<Glib>, L<Glib::ParamSpec>, L<Glib::ParamSpec>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2011 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Glib> for a full notice.



=cut

