=head1 NAME

Glib::Param::GType - Wrapper for type parameters in GLib

=cut

=head1 HIERARCHY

  Glib::ParamSpec
  +----Glib::Param::GType



=cut

=for object Glib::Param::GType - Wrapper for type parameters in GLib

=for section DESCRIPTION

=head1 DESCRIPTION

This object describes a parameter which holds the name of a class known to the
GLib type system.  The name of the class is considered to be the common
ancestor for valid values.  To create a param that allows any type name,
specify C<undef> for the package name.  Beware, however, that although
we say "any type name", this actually refers to any type registered
with Glib; normal Perl packages will not work.

=cut




=head1 METHODS

=head2 string or undef = $pspec_gtype-E<gt>B<get_is_a_type> 

If C<undef>, then any class is allowed.

Since: glib 2.10



=cut


=head1 SEE ALSO

L<Glib>, L<Glib::ParamSpec>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2011 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Glib> for a full notice.



=cut

