=head1 NAME

Glib::Param::Int - Paramspecs for integer types

=cut

=head1 HIERARCHY

  Glib::ParamSpec
  +----Glib::Param::Int



=cut

=for object Glib::Param::Int - Paramspecs for integer types

=for position post_hierarchy

  Glib::ParamSpec
  +----Glib::Param::Char

  Glib::ParamSpec
  +----Glib::Param::Long

=cut

=head1 DESCRIPTION

This page documents the extra accessors available for all of the integer type
paramspecs: Char, Int, and Long.  Perl really only supports full-size integers,
so all of these methods return IVs; the distinction of integer size is
important to the underlying C library and also determines the data value range.

=cut




=head1 METHODS

=head2 integer = $pspec-E<gt>B<get_maximum> 

=head2 integer = $pspec-E<gt>B<get_minimum> 



=cut


=head1 SEE ALSO

L<Glib>, L<Glib::ParamSpec>, L<Glib::ParamSpec>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2011 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Glib> for a full notice.



=cut

