=head1 NAME

Glib::Param::Unichar -  Wrapper for unichar parameters in GLib

=cut

=head1 HIERARCHY

  Glib::ParamSpec
  +----Glib::Param::Unichar



=cut

=for object Glib::Param::Unichar Wrapper for unichar parameters in GLib
=cut




=head1 METHODS

=head2 double = $pspec-E<gt>B<get_epsilon> 

=head2 double = $pspec-E<gt>B<get_maximum> 

=head2 double = $pspec-E<gt>B<get_minimum> 



=cut


=head1 SEE ALSO

L<Glib>, L<Glib::ParamSpec>, L<Glib::ParamSpec>


=cut


=head1 COPYRIGHT

Copyright (C) 2003-2011 by the gtk2-perl team.

This software is licensed under the LGPL.  See L<Glib> for a full notice.



=cut

