#!/bin/sh
set -e

. /usr/share/os-prober/common.sh

partition="$1"
dir="$2"
type="$3"

if [ -d "$dir/servers" ] && [ -d "$dir/hurd" ]; then
        label="$(count_next_label Hurd)"
	result "$partition:GNU/Hurd:$label:hurd"
	exit 0
else
	exit 1
fi
