# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5DBusAddons_QCH)

add_custom_target(KF5DBusAddons_QCH)
set_target_properties(KF5DBusAddons_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5DBusAddons.tags"
    QHP_NAMESPACE "org.kde.KDBusAddons"
    QHP_NAMESPACE_VERSIONED "org.kde.KDBusAddons.5_64_0"
    QHP_VIRTUALFOLDER "kdbusaddons"
    IMPORTED TRUE
)
set_property(TARGET KF5DBusAddons_QCH PROPERTY LINK_QCHS Qt5DBus_QCH;Qt5Core_QCH)

endif()
