# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5IconThemes_QCH)

add_custom_target(KF5IconThemes_QCH)
set_target_properties(KF5IconThemes_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5IconThemes.tags"
    QHP_NAMESPACE "org.kde.KIconThemes"
    QHP_NAMESPACE_VERSIONED "org.kde.KIconThemes.5_64_0"
    QHP_VIRTUALFOLDER "kiconthemes"
    IMPORTED TRUE
)
set_property(TARGET KF5IconThemes_QCH PROPERTY LINK_QCHS Qt5Widgets_QCH)

endif()
