#!/bin/sh

. /usr/share/debconf/confmodule

cd $1

num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

if [ "$fs" != free ]; then
	db_metaget partman/text/number description
	printf "\${!ALIGN=RIGHT}$RET" $num
fi
