#!/bin/sh

. /usr/share/debconf/confmodule
. /lib/partman/lib/base.sh

cd $1

num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

open_dialog USES_EXTENDED
read_line x
close_dialog

if [ "$x" = "yes" ]; then
	db_metaget "partman/text/$type" description

	printf %s "$RET"
fi
