#!/bin/sh

cd $1

num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

if [ -f $id/method ]; then
	if [ -f $id/format ]; then
		if [ -f $id/detected_filesystem ]; then
			printf "F"
		else
			printf "f"
		fi
	else
		printf "K"
	fi
fi
