#!/bin/sh

. /lib/partman/lib/base.sh

cd $1

num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
shift; shift; shift; shift; shift; shift; shift
name=$*

open_dialog USES_NAMES
read_line x
close_dialog

if [ "$x" = yes ]; then
	printf "%.12s" "$name"
fi
