#!/bin/sh

. /lib/partman/lib/base.sh

dev="$2"
id=$3

[ -f $dev/$id/method ] || exit 0
method=$(cat $dev/$id/method)

case "$method" in
    keep)
	echo format >$dev/$id/method
	> $dev/$id/format
	> $dev/$id/use_filesystem
	;;
    format)
	echo keep >$dev/$id/method
	rm -f $dev/$id/format
	> $dev/$id/use_filesystem
	;;
esac

update_partition $dev $id
