#!/bin/sh

. /lib/partman/lib/base.sh
. /lib/partman/lib/recipes.sh
. /lib/partman/lib/crypto-base.sh

# If there are no recipies that support LVM then don't offer auto-crypto
recipedir=$(get_recipedir)
if ! grep -q "\$lvmok" $recipedir/*; then
	exit 0
fi

# Also don't offer auto-crypto if there is not enough memory
crypto_check_mem false || exit 0

db_metaget partman-auto-crypto/text/choice description
printf "crypto\t$RET\n"
