# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Completion_QCH)

add_custom_target(KF5Completion_QCH)
set_target_properties(KF5Completion_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5Completion.tags"
    QHP_NAMESPACE "org.kde.KCompletion"
    QHP_NAMESPACE_VERSIONED "org.kde.KCompletion.5_64_0"
    QHP_VIRTUALFOLDER "kcompletion"
    IMPORTED TRUE
)
set_property(TARGET KF5Completion_QCH PROPERTY LINK_QCHS Qt5Core_QCH;Qt5Gui_QCH;Qt5Widgets_QCH)

endif()
