#!/bin/sh

. /lib/partman/lib/base.sh
. /lib/partman/lib/recipes.sh

# If there are no recipies that support LVM then don't offer auto-lvm
recipedir=$(get_recipedir)
if ! grep -q "\$lvmok" $recipedir/*; then
	exit 0
fi

# If LVM support is not available then don't offer auto-lvm
[ -f /var/lib/partman/lvm ] || exit 0

db_metaget partman-auto-lvm/text/choice description
printf "lvm\t$RET\n"
