#!/bin/sh

. /lib/partman/lib/base.sh

dev="$2"
id=$3

cd $dev

open_dialog GET_CHS $id
read_line cs hs ss ce he se
close_dialog

db_subst partman/show_free_chs FROMCHS "($cs,$hs,$ss)"
db_subst partman/show_free_chs TOCHS "($ce,$he,$se)"

db_input critical partman/show_free_chs || true
db_go || true
