#!/bin/sh

dev=$2
id=$3

mkdir -p $dev/$id

if [ -f $dev/$id/method ]; then
	old_method=$(cat $dev/$id/method)
else
	old_method=do_not_use
fi

echo swap >$dev/$id/method
>$dev/$id/format
rm -f $dev/$id/use_filesystem
