# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Notifications_QCH)

add_custom_target(KF5Notifications_QCH)
set_target_properties(KF5Notifications_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5Notifications.tags"
    QHP_NAMESPACE "org.kde.KNotifications"
    QHP_NAMESPACE_VERSIONED "org.kde.KNotifications.5_64_0"
    QHP_VIRTUALFOLDER "knotifications"
    IMPORTED TRUE
)
set_property(TARGET KF5Notifications_QCH PROPERTY LINK_QCHS Qt5Widgets_QCH)

endif()
