// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KCrash_VERSION_H
#define KCrash_VERSION_H

#define KCrash_VERSION_STRING "5.64.0"
#define KCrash_VERSION_MAJOR 5
#define KCrash_VERSION_MINOR 64
#define KCrash_VERSION_PATCH 0
#define KCrash_VERSION ((5<<16)|(64<<8)|(0))

#endif
