// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KI18N_VERSION_H
#define KI18N_VERSION_H

#define KI18N_VERSION_STRING "5.64.0"
#define KI18N_VERSION_MAJOR 5
#define KI18N_VERSION_MINOR 64
#define KI18N_VERSION_PATCH 0
#define KI18N_VERSION ((5<<16)|(64<<8)|(0))

#endif
