// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KIO_VERSION_H
#define KIO_VERSION_H

#define KIO_VERSION_STRING "5.64.0"
#define KIO_VERSION_MAJOR 5
#define KIO_VERSION_MINOR 64
#define KIO_VERSION_PATCH 0
#define KIO_VERSION ((5<<16)|(64<<8)|(0))

#endif
