// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef KXMLGUI_VERSION_H
#define KXMLGUI_VERSION_H

#define KXMLGUI_VERSION_STRING "5.64.0"
#define KXMLGUI_VERSION_MAJOR 5
#define KXMLGUI_VERSION_MINOR 64
#define KXMLGUI_VERSION_PATCH 0
#define KXMLGUI_VERSION ((5<<16)|(64<<8)|(0))

#endif
