// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef SONNET_VERSION_H
#define SONNET_VERSION_H

#define SONNET_VERSION_STRING "5.64.0"
#define SONNET_VERSION_MAJOR 5
#define SONNET_VERSION_MINOR 64
#define SONNET_VERSION_PATCH 0
#define SONNET_VERSION ((5<<16)|(64<<8)|(0))

#endif
