#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# busybox
if [ "${BUSYBOX}" = "n" ]; then
	exit 0
fi
if ! [ -e ${BUSYBOXDIR}/busybox ]; then
	if [ "${BUSYBOX}" = "y" ]; then
		echo >&2 "E: busybox is required but not installed"
		exit 1
	else
		exit 0
	fi
fi
. /usr/share/initramfs-tools/hook-functions
rm -f ${DESTDIR}/bin/sh
rm -f ${DESTDIR}/bin/busybox
copy_exec ${BUSYBOXDIR}/busybox /bin/busybox
ln -s busybox ${DESTDIR}/bin/sh
