#!/bin/sh

set -e

PREREQ=""

# Output pre-requisites
prereqs()
{
        echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/parted /sbin
copy_exec /sbin/sgdisk /sbin
copy_exec /sbin/resize2fs /sbin
copy_exec /sbin/blockdev /sbin
copy_exec /usr/bin/realpath
copy_exec /usr/bin/dirname
