#!/bin/sh

set -e

PREREQ=""

# Output pre-requisites
prereqs()
{
        echo "$PREREQ"
}

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /bin/chown
copy_exec /sbin/findfs
copy_exec /sbin/e2fsck
copy_exec /usr/bin/abootimg

manual_add_modules squashfs
