# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Auth_QCH)

add_custom_target(KF5Auth_QCH)
set_target_properties(KF5Auth_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5Auth.tags"
    QHP_NAMESPACE "org.kde.KAuth"
    QHP_NAMESPACE_VERSIONED "org.kde.KAuth.5_64_0"
    QHP_VIRTUALFOLDER "kauth"
    IMPORTED TRUE
)
set_property(TARGET KF5Auth_QCH PROPERTY LINK_QCHS Qt5Core_QCH;KF5CoreAddons_QCH)

endif()
