# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Config_QCH)

add_custom_target(KF5Config_QCH)
set_target_properties(KF5Config_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5Config.tags"
    QHP_NAMESPACE "org.kde.KConfig"
    QHP_NAMESPACE_VERSIONED "org.kde.KConfig.5_64_0"
    QHP_VIRTUALFOLDER "kconfig"
    IMPORTED TRUE
)
set_property(TARGET KF5Config_QCH PROPERTY LINK_QCHS Qt5Core_QCH;Qt5Xml_QCH;Qt5Gui_QCH)

endif()
