#!/bin/sh

. /lib/partman/lib/base.sh

for dev in $DEVICES/*; do
	[ -d "$dev" ] || continue
	cd $dev
	partitions=
	open_dialog PARTITIONS
	while { read_line num id size type fs path name; [ "$id" ]; }; do
		[ "$fs" != free ] || continue
		partitions="$partitions $id,$num"
	done
	close_dialog

	for part in $partitions; do
		id=${part%,*}
		num=${part#*,}
		[ -f $id/method ] || continue
		[ -f $id/acting_filesystem ] || continue
		filesystem=$(cat $id/acting_filesystem)
		case "$filesystem" in
		    xfs)
			[ ! -f "$id/mountpoint" ] || continue
			T=partman-basicfilesystems/no_mount_point
			db_subst $T PARTITION "$num"
			db_subst $T FILESYSTEM "$filesystem"
			db_subst $T DEVICE $(humandev $(cat device))
			db_input critical $T || true
			db_go || exit 1
			db_get $T
			if [ "$RET" = true ]; then
				exit 1
			fi
			;;
		esac
	done
done
