#!/bin/sh

. /lib/partman/lib/base.sh

swap=false

for dev in $DEVICES/*; do
	[ -d "$dev" ] || continue
	cd $dev
	partitions=
	open_dialog PARTITIONS
	while { read_line num id size type fs path name; [ "$id" ]; }; do
		[ "$fs" != free ] || continue
		partitions="$partitions $id,$num"
	done
	close_dialog

	for part in $partitions; do
		id=${part%,*}
		num=${part#*,}
		[ -f $id/method ] || continue
		method=$(cat $id/method)
		if [ "$method" = swap ]; then
			swap=:
		fi
	done
done

if ! $swap; then
	db_input medium partman-basicfilesystems/no_swap || true
	db_go || true
	db_get partman-basicfilesystems/no_swap
	if [ "$RET" = true ]; then
		exit 1
	fi
fi
