#!/bin/sh

. /lib/partman/lib/base.sh

dev=$1
id=$2
cd $dev

if [ -f $id/method ]; then
	method=$(cat $id/method)
else
	method=dont_use
fi

if [ -f $id/filesystem ] && \
   ([ "$method" = keep ] || [ "$method" = format ]); then
	fs=$(cat $id/filesystem)
	db_metaget partman/filesystem_long/$fs description || RET=''
	description="${RET:-$fs}"
else
	db_metaget partman/method_long/$method description || RET=''
	description="${RET:-$method}"
fi

db_metaget partman-target/text/method description
printf "method\t%s\${!TAB}%s\n" "${RET}" "$description"
