#!/bin/sh

mkdir -p /var/lib/partman

cat /proc/modules |
while read module_name x; do
	if [ "$module_name" = ext3 ]; then
		>/var/lib/partman/ext3
	fi
	if [ "$module_name" = ext4 ]; then
		>/var/lib/partman/ext4
	fi
done

if ! [ -f /var/lib/partman/ext3 ] && \
   modprobe ext3 >/dev/null 2>/dev/null; then
	>/var/lib/partman/ext3
fi

if ! [ -f /var/lib/partman/ext4 ] && \
   modprobe ext4 >/dev/null 2>/dev/null; then
	>/var/lib/partman/ext4
fi

if ! [ -f /var/lib/partman/ext3 ] && \
   grep -q ext3 /proc/filesystems; then
	>/var/lib/partman/ext3
fi

if ! [ -f /var/lib/partman/ext4 ] && \
   grep -q ext4 /proc/filesystems; then
	>/var/lib/partman/ext4
fi
