#!/bin/sh

. /lib/partman/lib/base.sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

cd $dev

if [ $fs = free ]; then
	rm -f $id/bootable
else
	bootable=no
	open_dialog GET_FLAGS $id
	while { read_line flag; [ "$flag" ]; }; do
		if [ "$flag" = boot ]; then
			bootable=yes
		fi
	done
	close_dialog

	if [ $bootable = yes ]; then
		mkdir -p $id
		>$id/bootable
	else
		rm -f $id/bootable
	fi
fi
