#!/bin/sh

. /lib/partman/lib/base.sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

cd $dev

[ -f $id/method ] || exit 0
method=$(cat $id/method)

case "$method" in
    keep|format)
	if [ -f $id/acting_filesystem ]; then
		filesystem=$(cat $id/acting_filesystem)
		db_metaget partman/filesystem_short/"$filesystem" description || RET=''
		printf "${RET:-$filesystem}" >$id/visual_filesystem
	else
		>$id/visual_filesystem
	fi
	if [ -f $id/mountpoint ]; then
		cat $id/mountpoint >$id/visual_mountpoint
	else
		>$id/visual_mountpoint
	fi
	;;
esac
