#!/bin/sh

. /lib/partman/lib/base.sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

cd $dev

[ -f $id/method ] || exit 0
method=$(cat $id/method)

case "$method" in
    lvm)
	db_metaget partman/method_short/lvm description || RET=''
	printf "${RET:-lvm}" >$id/visual_filesystem
	>$id/visual_mountpoint
	;;
esac
