#!/bin/sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
shift; shift; shift; shift; shift; shift; shift
name=$*

cd $dev

mkdir -p $id

for v in /lib/partman/visual.d/*; do
	[ -x "$v" ] || continue
	$v $dev $num $id $size $type $fs $path $name
	printf '${!TAB}'
done >$id/view
