/* This file was generated by syncqt. */
#ifndef QT_QTUITOOLS_VERSION_H
#define QT_QTUITOOLS_VERSION_H

#define QTUITOOLS_VERSION_STR "5.13.2"

#define QTUITOOLS_VERSION 0x050D02

#endif // QT_QTUITOOLS_VERSION_H
