#!/bin/sh
# Check if apport reports are enabled. Exit with 0 if so, otherwise with 1.
#
# Copyright (c) 2011 Canonical Ltd.
# Author: Martin Pitt <martin.pitt@ubuntu.com>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See http://www.gnu.org/copyleft/gpl.html for
# the full text of the license.

set -e

CONF=/etc/default/apport

# defaults to enabled if not present
[ -f $CONF ] || exit 0
! grep -q '^[[:space:]]*enabled[[:space:]]*=[[:space:]]*0[[:space:]]*$' $CONF
