# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5KIO_QCH)

add_custom_target(KF5KIO_QCH)
set_target_properties(KF5KIO_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5KIO.tags"
    QHP_NAMESPACE "org.kde.KIO"
    QHP_NAMESPACE_VERSIONED "org.kde.KIO.5_64_0"
    QHP_VIRTUALFOLDER "kio"
    IMPORTED TRUE
)
set_property(TARGET KF5KIO_QCH PROPERTY LINK_QCHS KF5CoreAddons_QCH;KF5Service_QCH;Qt5Widgets_QCH;Qt5Network_QCH;KF5Completion_QCH;KF5WidgetsAddons_QCH;KF5JobWidgets_QCH;KF5Bookmarks_QCH;KF5ItemViews_QCH;KF5XmlGui_QCH;KF5Solid_QCH)

endif()
