QT.KConfigGui.VERSION = 5.64.0
QT.KConfigGui.MAJOR_VERSION = 5
QT.KConfigGui.MINOR_VERSION = 64
QT.KConfigGui.PATCH_VERSION = 0
QT.KConfigGui.name = KF5ConfigGui
QT.KConfigGui.module = KF5ConfigGui
QT.KConfigGui.defines = 
QT.KConfigGui.includes = /usr/include/KF5/KConfigGui
QT.KConfigGui.private_includes =
QT.KConfigGui.libs = /usr/lib/x86_64-linux-gnu
QT.KConfigGui.depends = gui xml KConfigCore
