QT.KJobWidgets.VERSION = 5.64.0
QT.KJobWidgets.MAJOR_VERSION = 5
QT.KJobWidgets.MINOR_VERSION = 64
QT.KJobWidgets.PATCH_VERSION = 0
QT.KJobWidgets.name = KF5JobWidgets
QT.KJobWidgets.module = KF5JobWidgets
QT.KJobWidgets.defines = 
QT.KJobWidgets.includes = /usr/include/KF5/KJobWidgets
QT.KJobWidgets.private_includes =
QT.KJobWidgets.libs = /usr/lib/x86_64-linux-gnu
QT.KJobWidgets.depends = widgets KCoreAddons
