QT.KIOWidgets.VERSION = 5.64.0
QT.KIOWidgets.MAJOR_VERSION = 5
QT.KIOWidgets.MINOR_VERSION = 64
QT.KIOWidgets.PATCH_VERSION = 0
QT.KIOWidgets.name = KF5KIOWidgets
QT.KIOWidgets.module = KF5KIOWidgets
QT.KIOWidgets.defines = 
QT.KIOWidgets.includes = /usr/include/KF5/KIOWidgets
QT.KIOWidgets.private_includes =
QT.KIOWidgets.libs = /usr/lib/x86_64-linux-gnu
QT.KIOWidgets.depends = KIOCore KBookmarks KXmlGui Solid
