QT.KConfigCore.VERSION = 5.64.0
QT.KConfigCore.MAJOR_VERSION = 5
QT.KConfigCore.MINOR_VERSION = 64
QT.KConfigCore.PATCH_VERSION = 0
QT.KConfigCore.name = KF5ConfigCore
QT.KConfigCore.module = KF5ConfigCore
QT.KConfigCore.defines = 
QT.KConfigCore.includes = /usr/include/KF5/KConfigCore
QT.KConfigCore.private_includes =
QT.KConfigCore.libs = /usr/lib/x86_64-linux-gnu
QT.KConfigCore.depends = core
