QT.KXmlGui.VERSION = 5.64.0
QT.KXmlGui.MAJOR_VERSION = 5
QT.KXmlGui.MINOR_VERSION = 64
QT.KXmlGui.PATCH_VERSION = 0
QT.KXmlGui.name = KF5XmlGui
QT.KXmlGui.module = KF5XmlGui
QT.KXmlGui.defines = 
QT.KXmlGui.includes = /usr/include/KF5/KXmlGui
QT.KXmlGui.private_includes =
QT.KXmlGui.libs = /usr/lib/x86_64-linux-gnu
QT.KXmlGui.depends = dbus xml widgets KConfigCore KConfigWidgets
