QT.KTextWidgets.VERSION = 5.64.0
QT.KTextWidgets.MAJOR_VERSION = 5
QT.KTextWidgets.MINOR_VERSION = 64
QT.KTextWidgets.PATCH_VERSION = 0
QT.KTextWidgets.name = KF5TextWidgets
QT.KTextWidgets.module = KF5TextWidgets
QT.KTextWidgets.defines = 
QT.KTextWidgets.includes = /usr/include/KF5/KTextWidgets
QT.KTextWidgets.private_includes =
QT.KTextWidgets.libs = /usr/lib/x86_64-linux-gnu
QT.KTextWidgets.depends = widgets SonnetUi KI18n
