QT.KNotifications.VERSION = 5.64.0
QT.KNotifications.MAJOR_VERSION = 5
QT.KNotifications.MINOR_VERSION = 64
QT.KNotifications.PATCH_VERSION = 0
QT.KNotifications.name = KF5Notifications
QT.KNotifications.module = KF5Notifications
QT.KNotifications.defines = 
QT.KNotifications.includes = /usr/include/KF5/KNotifications
QT.KNotifications.private_includes =
QT.KNotifications.libs = /usr/lib/x86_64-linux-gnu
QT.KNotifications.depends = widgets
