QT.KItemViews.VERSION = 5.64.0
QT.KItemViews.MAJOR_VERSION = 5
QT.KItemViews.MINOR_VERSION = 64
QT.KItemViews.PATCH_VERSION = 0
QT.KItemViews.name = KF5ItemViews
QT.KItemViews.module = KF5ItemViews
QT.KItemViews.defines = 
QT.KItemViews.includes = /usr/include/KF5/KItemViews
QT.KItemViews.private_includes =
QT.KItemViews.libs = /usr/lib/x86_64-linux-gnu
QT.KItemViews.depends = widgets
