QT.Solid.VERSION = 5.64.0
QT.Solid.MAJOR_VERSION = 5
QT.Solid.MINOR_VERSION = 64
QT.Solid.PATCH_VERSION = 0
QT.Solid.name = KF5Solid
QT.Solid.module = KF5Solid
QT.Solid.defines = 
QT.Solid.includes = /usr/include/KF5/Solid
QT.Solid.private_includes =
QT.Solid.libs = /usr/lib/x86_64-linux-gnu
QT.Solid.depends = core
