# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5SonnetCore_QCH)

add_custom_target(KF5SonnetCore_QCH)
set_target_properties(KF5SonnetCore_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5SonnetCore.tags"
    QHP_NAMESPACE "org.kde.SonnetCore"
    QHP_NAMESPACE_VERSIONED "org.kde.SonnetCore.5_64_0"
    QHP_VIRTUALFOLDER "sonnetcore"
    IMPORTED TRUE
)
set_property(TARGET KF5SonnetCore_QCH PROPERTY LINK_QCHS Qt5Core_QCH)

endif()

if (NOT TARGET KF5SonnetUi_QCH)

add_custom_target(KF5SonnetUi_QCH)
set_target_properties(KF5SonnetUi_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5SonnetUi.tags"
    QHP_NAMESPACE "org.kde.SonnetUi"
    QHP_NAMESPACE_VERSIONED "org.kde.SonnetUi.5_64_0"
    QHP_VIRTUALFOLDER "sonnetui"
    IMPORTED TRUE
)
set_property(TARGET KF5SonnetUi_QCH PROPERTY LINK_QCHS Qt5Core_QCH;Qt5Gui_QCH;Qt5Widgets_QCH)

endif()
