# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5Solid_QCH)

add_custom_target(KF5Solid_QCH)
set_target_properties(KF5Solid_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5Solid.tags"
    QHP_NAMESPACE "org.kde.Solid"
    QHP_NAMESPACE_VERSIONED "org.kde.Solid.5_64_0"
    QHP_VIRTUALFOLDER "solid"
    IMPORTED TRUE
)
set_property(TARGET KF5Solid_QCH PROPERTY LINK_QCHS Qt5Core_QCH)

endif()
