#! /bin/sh

set -e

dpkg-maintscript-helper rm_conffile \
    /etc/colord.conf 1.2.12-1~ colord -- "$@"

# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.freedesktop.colord-sane.conf 1.0.3-1~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/colormgr-completion.bash 1.0.3-1~ -- "$@"
# End automatically added section


exit 0
