#!/bin/sh
set -e
# Automatically added by dh_installxmlcatalogs
if [ "$1" = "remove" ] || [ "$1" = "upgrade" ]; then
	update-xmlcatalog --del --type uri --id "http://docbook.sourceforge.net/release/xsl/" --root || true
	update-xmlcatalog --del --type system --id "http://docbook.sourceforge.net/release/xsl/" --root || true

	update-xmlcatalog --del --type uri --id "http://docbook.sourceforge.net/release/xsl/" --package docbook-xsl || true
	update-xmlcatalog --del --type system --id "http://docbook.sourceforge.net/release/xsl/" --package docbook-xsl || true

fi
# End automatically added section
