#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.4ubuntu1
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.d/89-tlwg-loma-synthetic.conf 1:0.6.3-1\~ fonts-tlwg-loma -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/89-tlwg-loma-synthetic.conf 1:0.6.3-1\~ fonts-tlwg-loma -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.d/64-12-tlwg-loma.conf 1:0.6.3-1\~ fonts-tlwg-loma -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/64-12-tlwg-loma.conf 1:0.6.3-1\~ fonts-tlwg-loma -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/64-10-tlwg-loma.conf 1:0.6.4-2\~ fonts-tlwg-loma -- "$@"
# End automatically added section
