#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.4ubuntu1
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.d/89-tlwg-waree-synthetic.conf 1:0.6.3-1\~ fonts-tlwg-waree -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/89-tlwg-waree-synthetic.conf 1:0.6.3-1\~ fonts-tlwg-waree -- "$@"
dpkg-maintscript-helper rm_conffile /etc/fonts/conf.avail/64-11-tlwg-waree.conf 1:0.6.4-2\~ fonts-tlwg-waree -- "$@"
# End automatically added section
