#!/bin/sh
set -e

# Automatically added by dh_systemd_start/11.1.6ubuntu2
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


if [ "$1" = purge ]; then
	rm -rf /var/lib/fwupd/gnupg
	rm -f /var/cache/app-info/xmls/fwupd.xml
fi

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
	dpkg-maintscript-helper rm_conffile \
		/etc/fwupd.conf 1.0.0~ -- "$@"
fi
