#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.gnome.SettingsDaemon.DateTimeMechanism.conf 3.8.2-2\~ gnome-settings-daemon -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/org.gnome.SettingsDaemon.XRANDR.desktop 3.25.91-0ubuntu2\~ gnome-settings-daemon -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/org.gnome.SettingsDaemon.Orientation.desktop 3.25.91-0ubuntu2\~ gnome-settings-daemon -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/org.gnome.SettingsDaemon.A11yKeyboard.desktop 3.27.90-0ubuntu0\~ gnome-settings-daemon -- "$@"
# End automatically added section
