#!/bin/sh
set -e
# Automatically added by dh_systemd_start/11.1.3ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		deb-systemd-invoke start 'iio-sensor-proxy.service' >/dev/null || true
	fi
fi
# End automatically added section
