#! /bin/sh

set -e

case "$1" in
    install)
    ;;

    remove|purge)
    ;;

    upgrade|failed-upgrade)
	if dpkg --compare-versions "$2" lt "0.5.0+git1.656f8865-7"; then
	   [ -e /var/lib/dpkg/info/kpartx.prerm ] && rm /var/lib/dpkg/info/kpartx.prerm
	fi
    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac



exit 0

