#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.kde.ktexteditor.katetextbuffer.conf -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/katemoderc 5.16.0-1\~\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/kateschemarc 5.16.0-1\~\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/katesyntaxhighlightingrc 5.16.0-1\~\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/ktexteditor.categories 5.52.0-1 -- "$@"
# End automatically added section
