#!/bin/sh

set -e

case "$1" in
    upgrade)
        if dpkg --compare-versions "$2" lt 2.02.122-2; then
            if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper purge lvm2-activation.service lvm2-activation-early.service >/dev/null
                deb-systemd-helper unmask lvm2-activation.service lvm2-activation-early.service >/dev/null
            fi
        fi
    ;;
esac



exit 0
