#!/bin/sh -e

if [ "$1" = "configure" ]; then
    update-alternatives \
        --install /bin/nc nc /bin/nc.openbsd 50 \
        --slave /bin/netcat netcat /bin/nc.openbsd \
        --slave /usr/share/man/man1/nc.1.gz nc.1.gz \
                /usr/share/man/man1/nc_openbsd.1.gz \
        --slave /usr/share/man/man1/netcat.1.gz netcat.1.gz \
                /usr/share/man/man1/nc_openbsd.1.gz
fi


