#! /bin/sh

set -e

if [ "$1" = configure ]; then
	update-alternatives --quiet \
	  --install /usr/bin/pinentry pinentry /usr/bin/pinentry-gnome3 90 \
	  --slave /usr/share/man/man1/pinentry.1.gz pinentry.1.gz /usr/share/man/man1/pinentry-gnome3.1.gz
	update-alternatives --quiet \
	  --install /usr/bin/pinentry-x11 pinentry-x11 /usr/bin/pinentry-gnome3 90 \
	  --slave /usr/share/man/man1/pinentry-x11.1.gz pinentry-x11.1.gz /usr/share/man/man1/pinentry-gnome3.1.gz
fi


