#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.kde.fontinst.conf -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/org.kde.kcontrol.kcmclock.conf -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/colorschemes.knsrc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/emoticons.knsrc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/icons.knsrc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/kfontinst.knsrc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/ksplash.knsrc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/lookandfeel.knsrc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/plasma-desktop.categories -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/plasma-themes.knsrc -- "$@"
dpkg-maintscript-helper rm_conffile /etc/xdg/xcursor.knsrc -- "$@"
# End automatically added section
