#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu1
if [ -x "/etc/init.d/speech-dispatcher" ] && [ "$1" = remove ]; then
	invoke-rc.d speech-dispatcher stop || true
fi
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu1
dpkg-maintscript-helper rm_conffile /etc/speech-dispatcher/clients/gnome-speech.conf 0.8.6-2\~ speech-dispatcher -- "$@"
# End automatically added section
