#!/bin/sh
set -e
# Automatically added by dh_systemd_start/10.10.9ubuntu1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'spice-vdagentd.target' >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9ubuntu1
if [ -x "/etc/init.d/spice-vdagent" ] && [ "$1" = remove ]; then
	invoke-rc.d spice-vdagent stop || exit $?
fi
# End automatically added section
