#!/bin/sh
set -e
# Automatically added by dh_systemd_enable/10.10.9ubuntu1
# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask 'spice-vdagentd.service' >/dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled 'spice-vdagentd.service'; then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable 'spice-vdagentd.service' >/dev/null || true
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state 'spice-vdagentd.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	# In case this system is running systemd, we need to ensure that all
	# necessary tmpfiles (if any) are created before starting.
	if [ -d /run/systemd/system ] ; then
		systemd-tmpfiles --create /usr/lib/tmpfiles.d/spice-vdagentd.conf >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installinit/10.10.9ubuntu1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
	if [ -x "/etc/init.d/spice-vdagent" ]; then
		update-rc.d spice-vdagent defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d spice-vdagent $_dh_action || exit $?
	fi
fi
# End automatically added section
# Automatically added by dh_systemd_start/10.10.9ubuntu1
if [ -d /run/systemd/system ]; then
	systemctl --system daemon-reload >/dev/null || true
	if [ -n "$2" ]; then
		_dh_action=restart
	else
		_dh_action=start
	fi
	deb-systemd-invoke $_dh_action 'spice-vdagentd.target' >/dev/null || true
fi
# End automatically added section
