#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.6ubuntu1
dpkg-maintscript-helper mv_conffile /etc/dbus-1/system.d/newprinternotification.conf /etc/dbus-1/system.d/com.redhat.NewPrinterNotification.conf 1.4.1-3\~ system-config-printer -- "$@"
dpkg-maintscript-helper mv_conffile /etc/dbus-1/system.d/printerdriversinstaller.conf /etc/dbus-1/system.d/com.redhat.PrinterDriversInstaller.conf 1.4.1-3\~ system-config-printer -- "$@"
# End automatically added section
