#!/bin/sh
set -e
# Automatically added by dh_installdeb/11.1.6ubuntu1
dpkg-maintscript-helper mv_conffile /etc/update-motd.d/99-esm /etc/update-motd.d/80-esm 15~ -- "$@"
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu1
dpkg-maintscript-helper mv_conffile /etc/update-motd.d/99-livepatch /etc/update-motd.d/80-livepatch 15~ -- "$@"
# End automatically added section
