#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu2
if [ -x "/etc/init.d/x11-common" ] && [ "$1" = remove ]; then
	invoke-rc.d x11-common stop || exit 1
fi
# End automatically added section
# Automatically added by dh_installdeb/11.1.6ubuntu2
dpkg-maintscript-helper rm_conffile /etc/X11/Xsession.d/00upstart 1:7.7\+19ubuntu5\~ upstart -- "$@"
dpkg-maintscript-helper rm_conffile /etc/X11/Xsession.d/99upstart 1:7.7\+19ubuntu5\~ upstart -- "$@"
# End automatically added section
