#!/bin/sh
# Debian xcursor-themes package post-installation script
# Copyright 2003 Daniel Stone, Branden Robinson.
# Licensed under the GNU General Public License, version 2.  See the file
# /usr/share/common-licenses/GPL or <http://www.gnu.org/copyleft/gpl.txt>.
# Acknowledgements to Stephen Early, Mark Eichin, and Manoj Srivastava.

set -e

# register available X cursor themes with update-alternatives
update-alternatives --install /usr/share/icons/default/index.theme \
                              x-cursor-theme /etc/X11/cursors/core.theme 30
for THEME in redglass whiteglass handhelds; do
  update-alternatives --install /usr/share/icons/default/index.theme \
                                x-cursor-theme "/etc/X11/cursors/$THEME.theme" \
                                20
done



exit 0

# vim:set ai et sts=2 sw=2 tw=0:
