# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5CoreAddons_QCH)

add_custom_target(KF5CoreAddons_QCH)
set_target_properties(KF5CoreAddons_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5CoreAddons.tags"
    QHP_NAMESPACE "org.kde.KCoreAddons"
    QHP_NAMESPACE_VERSIONED "org.kde.KCoreAddons.5_64_0"
    QHP_VIRTUALFOLDER "kcoreaddons"
    IMPORTED TRUE
)
set_property(TARGET KF5CoreAddons_QCH PROPERTY LINK_QCHS Qt5Core_QCH)

endif()
