# This file was generated by ecm_install_qch_export(). DO NOT EDIT!

if (NOT TARGET KF5TextWidgets_QCH)

add_custom_target(KF5TextWidgets_QCH)
set_target_properties(KF5TextWidgets_QCH PROPERTIES
    DOXYGEN_TAGFILE "/usr/share/qt5/doc/KF5TextWidgets.tags"
    QHP_NAMESPACE "org.kde.KTextWidgets"
    QHP_NAMESPACE_VERSIONED "org.kde.KTextWidgets.5_64_0"
    QHP_VIRTUALFOLDER "ktextwidgets"
    IMPORTED TRUE
)
set_property(TARGET KF5TextWidgets_QCH PROPERTY LINK_QCHS Qt5Widgets_QCH;KF5SonnetUi_QCH;KF5I18n_QCH)

endif()
