#!/bin/sh

set -e

# Pretty echo, underline the specified string:
pecho() {
    echo "$@"
    echo "$@"|sed 's/./-/g'
}

# work even with graphicsmagick
# will detect graphickmagick using as compat
versioncheck() {
    if test -x "/usr/bin/$@"; then
	echo -n "$@: ";
	"$@" -version 2> /dev/null | head -1 | sed s/Version://g;
    fi
}

exec >&3

pecho "ImageMagick program version"
versioncheck animate
versioncheck compare
versioncheck convert
versioncheck composite
versioncheck conjure
versioncheck display
versioncheck identify
versioncheck import
versioncheck mogrify
versioncheck montage
versioncheck stream
